
project_id = "60a5196c-a2a2-4bd7-ad67-f5457c79a8c9"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
pop3_port = 54326
smtp_port = 54327

[functions.send-daily-digest]
verify_jwt = false

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_manual_linking = false
enable_signup = true
enable_anonymous_users = false
minimum_password_length = 6
password_requirements = "letters_digits"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template_path = "./supabase/templates"

[auth.sms]
enable_signup = true
enable_confirmations = false
template_path = "./supabase/templates"
test_otp = "123456"

[edge_runtime]
enabled = true
ip_version = "ipv4"
policy = "per_request"
inspector_port = 8083

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"
