// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brlvephljobxfivqlope.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJybHZlcGhsam9ieGZpdnFsb3BlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4Mjc4MTYsImV4cCI6MjA2NzQwMzgxNn0.w9o1ohRzYr75s3VRmwoQFPzf0NejH8Gvqg_4SvsAhYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});